using System.Data;
using System.Text.RegularExpressions;
using Kommand.Abstractions;
using Codewrinkles.Application.Common.Interfaces;
using Codewrinkles.Domain.Pulse;

namespace Codewrinkles.Application.Pulse;

public sealed record CreateRepulseCommand(
    Guid AuthorId,
    Guid RepulsedPulseId,
    string Content,
    Stream? ImageStream = null
) : ICommand<CreatePulseResult>;

public sealed class CreateRepulseCommandHandler
    : ICommandHandler<CreateRepulseCommand, CreatePulseResult>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IPulseImageService _pulseImageService;
    private readonly IProfileRepository _profileRepository;

    public CreateRepulseCommandHandler(
        IUnitOfWork unitOfWork,
        IPulseImageService pulseImageService,
        IProfileRepository profileRepository)
    {
        _unitOfWork = unitOfWork;
        _pulseImageService = pulseImageService;
        _profileRepository = profileRepository;
    }

    public async Task<CreatePulseResult> HandleAsync(
        CreateRepulseCommand command,
        CancellationToken cancellationToken)
    {
        // Create Repulse entity (ID will be generated by EF Core during SaveChanges)
        var repulse = Domain.Pulse.Pulse.CreateRepulse(
            authorId: command.AuthorId,
            content: command.Content,
            repulsedPulseId: command.RepulsedPulseId);

        string? imageUrl = null;

        // Perform all database operations atomically within a transaction
        // Isolation Level: ReadCommitted
        // - Prevents dirty reads (other transactions won't see incomplete Repulse without Engagement)
        // - No unnecessary locking (we're only doing inserts and single update)
        await using var transaction = await _unitOfWork.BeginTransactionAsync(
            IsolationLevel.ReadCommitted,
            cancellationToken);
        try
        {
            // 1. Create Repulse pulse
            _unitOfWork.Pulses.Create(repulse);
            await _unitOfWork.SaveChangesAsync(cancellationToken);
            // Repulse.Id is now available (generated by EF Core sequential GUID)

            // 2. Process and save image to disk (if provided)
            // This is a file I/O operation, not a database operation
            // If it fails, we'll rollback the transaction and clean up the file in catch block
            if (command.ImageStream is not null)
            {
                var (url, width, height) = await _pulseImageService.SavePulseImageAsync(
                    command.ImageStream,
                    repulse.Id,
                    cancellationToken);

                var pulseImage = PulseImage.Create(
                    pulseId: repulse.Id,
                    url: url,
                    width: width,
                    height: height);

                _unitOfWork.Pulses.CreateImage(pulseImage);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                imageUrl = url;
            }

            // 3. Create PulseEngagement for repulse with zero counts
            var engagement = PulseEngagement.Create(repulse.Id);
            _unitOfWork.Pulses.CreateEngagement(engagement);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            // 4. Extract and create mentions
            var mentionedHandles = ExtractMentions(repulse.Content);
            if (mentionedHandles.Count > 0)
            {
                var mentionedProfiles = await _profileRepository.FindByHandlesAsync(mentionedHandles, cancellationToken);
                foreach (var profile in mentionedProfiles)
                {
                    var mention = PulseMention.Create(repulse.Id, profile.Id, profile.Handle!);
                    _unitOfWork.Pulses.CreateMention(mention);

                    // Create mention notification (only if not mentioning self)
                    if (profile.Id != command.AuthorId)
                    {
                        var mentionNotification = Domain.Notification.Notification.CreateMentionNotification(
                            recipientId: profile.Id,
                            actorId: command.AuthorId,
                            pulseId: repulse.Id);
                        _unitOfWork.Notifications.Create(mentionNotification);
                    }
                }
                await _unitOfWork.SaveChangesAsync(cancellationToken);
            }

            // 5. Increment repulsed pulse's repulse count
            var repulsedEngagement = await _unitOfWork.Pulses.FindEngagementAsync(
                command.RepulsedPulseId,
                cancellationToken);
            // Repulsed engagement is guaranteed to exist (created with pulse)
            repulsedEngagement!.IncrementRepulseCount();
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            // 6. Create repulse notification (only if not repulsing own pulse)
            var repulsedPulse = await _unitOfWork.Pulses.FindByIdAsync(command.RepulsedPulseId, cancellationToken);
            if (repulsedPulse is not null && repulsedPulse.AuthorId != command.AuthorId)
            {
                var repulseNotification = Domain.Notification.Notification.CreateRepulseNotification(
                    recipientId: repulsedPulse.AuthorId,
                    actorId: command.AuthorId,
                    pulseId: repulse.Id);
                _unitOfWork.Notifications.Create(repulseNotification);
                await _unitOfWork.SaveChangesAsync(cancellationToken);
            }

            // Commit transaction - all entities created successfully
            // Database state is now consistent: Repulse + Engagement + (optional) Image + (optional) Mentions + Repulsed pulse count incremented
            await transaction.CommitAsync(cancellationToken);
        }
        catch
        {
            // Rollback on any error - no database records will be persisted
            await transaction.RollbackAsync(cancellationToken);

            // Clean up orphaned image file if it was saved to disk
            // The file I/O isn't part of the database transaction, so we must clean up manually
            if (imageUrl is not null)
            {
                _pulseImageService.DeletePulseImage(repulse.Id);
            }

            throw;
        }

        return new CreatePulseResult(
            PulseId: repulse.Id,
            Content: repulse.Content,
            CreatedAt: repulse.CreatedAt,
            ImageUrl: imageUrl
        );
    }

    private static List<string> ExtractMentions(string content)
    {
        // Regex to match @handle (alphanumeric + underscore, 3-30 chars)
        var mentionPattern = @"@(\w{3,30})";
        var matches = Regex.Matches(content, mentionPattern);

        return matches
            .Select(m => m.Groups[1].Value.ToLowerInvariant())
            .Distinct()
            .ToList();
    }
}
