using System.Data;
using System.Text.RegularExpressions;
using Kommand.Abstractions;
using Codewrinkles.Application.Common.Interfaces;
using Codewrinkles.Domain.Pulse;

namespace Codewrinkles.Application.Pulse;

public sealed record CreatePulseCommand(
    Guid AuthorId,
    string Content,
    Stream? ImageStream = null
) : ICommand<CreatePulseResult>;

public sealed record CreatePulseResult(
    Guid PulseId,
    string Content,
    DateTime CreatedAt,
    string? ImageUrl = null
);

public sealed class CreatePulseCommandHandler
    : ICommandHandler<CreatePulseCommand, CreatePulseResult>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IPulseImageService _pulseImageService;
    private readonly IProfileRepository _profileRepository;

    public CreatePulseCommandHandler(
        IUnitOfWork unitOfWork,
        IPulseImageService pulseImageService,
        IProfileRepository profileRepository)
    {
        _unitOfWork = unitOfWork;
        _pulseImageService = pulseImageService;
        _profileRepository = profileRepository;
    }

    public async Task<CreatePulseResult> HandleAsync(
        CreatePulseCommand command,
        CancellationToken cancellationToken)
    {
        // Create Pulse entity (ID will be generated by EF Core during SaveChanges)
        var pulse = Domain.Pulse.Pulse.Create(
            authorId: command.AuthorId,
            content: command.Content);

        string? imageUrl = null;

        // Perform all database operations atomically within a transaction
        // Isolation Level: ReadCommitted
        // - Prevents dirty reads (other transactions won't see incomplete Pulse without Engagement)
        // - No unnecessary locking (we're only doing inserts, no reads)
        await using var transaction = await _unitOfWork.BeginTransactionAsync(
            IsolationLevel.ReadCommitted,
            cancellationToken);
        try
        {
            // 1. Create Pulse
            _unitOfWork.Pulses.Create(pulse);
            await _unitOfWork.SaveChangesAsync(cancellationToken);
            // Pulse.Id is now available (generated by EF Core sequential GUID)

            // 2. Process and save image to disk (if provided)
            // This is a file I/O operation, not a database operation
            // If it fails, we'll rollback the transaction and clean up the file in catch block
            if (command.ImageStream is not null)
            {
                var (url, width, height) = await _pulseImageService.SavePulseImageAsync(
                    command.ImageStream,
                    pulse.Id,
                    cancellationToken);

                var pulseImage = PulseImage.Create(
                    pulseId: pulse.Id,
                    url: url,
                    width: width,
                    height: height);

                _unitOfWork.Pulses.CreateImage(pulseImage);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                imageUrl = url;
            }

            // 3. Create PulseEngagement with zero counts
            // This is REQUIRED - Pulse.Engagement relationship is configured as .IsRequired()
            // Without this, any query loading Pulse will fail with missing required navigation
            var engagement = PulseEngagement.Create(pulse.Id);
            _unitOfWork.Pulses.CreateEngagement(engagement);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            // 4. Extract and create mentions
            var mentionedHandles = ExtractMentions(pulse.Content);
            if (mentionedHandles.Count > 0)
            {
                var mentionedProfiles = await _profileRepository.FindByHandlesAsync(mentionedHandles, cancellationToken);
                foreach (var profile in mentionedProfiles)
                {
                    var mention = PulseMention.Create(pulse.Id, profile.Id, profile.Handle!);
                    _unitOfWork.Pulses.CreateMention(mention);
                }
                await _unitOfWork.SaveChangesAsync(cancellationToken);
            }

            // Commit transaction - all entities created successfully
            // Database state is now consistent: Pulse + Engagement + (optional) PulseImage + (optional) Mentions
            await transaction.CommitAsync(cancellationToken);
        }
        catch
        {
            // Rollback on any error - no database records will be persisted
            await transaction.RollbackAsync(cancellationToken);

            // Clean up orphaned image file if it was saved to disk
            // The file I/O isn't part of the database transaction, so we must clean up manually
            if (imageUrl is not null)
            {
                _pulseImageService.DeletePulseImage(pulse.Id);
            }

            throw;
        }

        return new CreatePulseResult(
            PulseId: pulse.Id,
            Content: pulse.Content,
            CreatedAt: pulse.CreatedAt,
            ImageUrl: imageUrl
        );
    }

    private static List<string> ExtractMentions(string content)
    {
        // Regex to match @handle (alphanumeric + underscore, 3-30 chars)
        var mentionPattern = @"@(\w{3,30})";
        var matches = Regex.Matches(content, mentionPattern);

        return matches
            .Select(m => m.Groups[1].Value.ToLowerInvariant())
            .Distinct()
            .ToList();
    }
}
