using System.Data;
using Kommand.Abstractions;
using Codewrinkles.Application.Common.Interfaces;
using Codewrinkles.Domain.Pulse;
using Codewrinkles.Telemetry;

namespace Codewrinkles.Application.Pulse;

public sealed record CreatePulseCommand(
    Guid AuthorId,
    string Content,
    Stream? ImageStream = null
) : ICommand<CreatePulseResult>;

public sealed record CreatePulseResult(
    Guid PulseId,
    string Content,
    DateTimeOffset CreatedAt,
    string? ImageUrl = null
);

public sealed class CreatePulseCommandHandler
    : ICommandHandler<CreatePulseCommand, CreatePulseResult>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IBlobStorageService _blobStorageService;
    private readonly IProfileRepository _profileRepository;
    private readonly ILinkPreviewService _linkPreviewService;
    private readonly PulseContentProcessor _contentProcessor;

    public CreatePulseCommandHandler(
        IUnitOfWork unitOfWork,
        IBlobStorageService blobStorageService,
        IProfileRepository profileRepository,
        ILinkPreviewService linkPreviewService,
        PulseContentProcessor contentProcessor)
    {
        _unitOfWork = unitOfWork;
        _blobStorageService = blobStorageService;
        _profileRepository = profileRepository;
        _linkPreviewService = linkPreviewService;
        _contentProcessor = contentProcessor;
    }

    public async Task<CreatePulseResult> HandleAsync(
        CreatePulseCommand command,
        CancellationToken cancellationToken)
    {
        using var activity = TelemetryExtensions.StartApplicationActivity(SpanNames.Pulse.Create);
        activity?.SetProfileId(command.AuthorId);

        try
        {
            // Create Pulse entity (ID will be generated by EF Core during SaveChanges)
            var pulse = Domain.Pulse.Pulse.Create(
                authorId: command.AuthorId,
                content: command.Content);

            string? imageUrl = null;
            var hasImage = command.ImageStream is not null;
            var mentionCount = 0;
            var hashtagCount = 0;
            var hasLink = false;

            // Perform all database operations atomically within a transaction
            // Isolation Level: ReadCommitted
            // - Prevents dirty reads (other transactions won't see incomplete Pulse without Engagement)
            // - No unnecessary locking (we're only doing inserts, no reads)
            await using var transaction = await _unitOfWork.BeginTransactionAsync(
                IsolationLevel.ReadCommitted,
                cancellationToken);
            try
            {
                // 1. Create Pulse
                _unitOfWork.Pulses.Create(pulse);
                await _unitOfWork.SaveChangesAsync(cancellationToken);
                // Pulse.Id is now available (generated by EF Core sequential GUID)

                activity?.SetEntity("Pulse", pulse.Id);

                // 2. Process and save image to blob storage (if provided)
                // Upload to Azure Blob Storage - if it fails, we'll rollback and clean up the blob
                if (command.ImageStream is not null)
                {
                    var (url, width, height) = await _blobStorageService.UploadPulseImageAsync(
                        command.ImageStream,
                        pulse.Id,
                        cancellationToken);

                    var pulseImage = PulseImage.Create(
                        pulseId: pulse.Id,
                        url: url,
                        width: width,
                        height: height);

                    _unitOfWork.Pulses.CreateImage(pulseImage);
                    await _unitOfWork.SaveChangesAsync(cancellationToken);

                    imageUrl = url;
                    AppMetrics.RecordImageUpload(imageType: "pulse", success: true);
                }

                // 3. Create PulseEngagement with zero counts
                // This is REQUIRED - Pulse.Engagement relationship is configured as .IsRequired()
                // Without this, any query loading Pulse will fail with missing required navigation
                var engagement = PulseEngagement.Create(pulse.Id);
                _unitOfWork.Pulses.CreateEngagement(engagement);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                // 4. Extract and create mentions
                var mentionResult = await _contentProcessor.ProcessMentionsAsync(
                    pulse.Id,
                    pulse.Content,
                    cancellationToken);

                // Create mention notifications (only if not mentioning self)
                foreach (var profile in mentionResult.MentionedProfiles)
                {
                    if (profile.Id != command.AuthorId)
                    {
                        var mentionNotification = Domain.Notification.Notification.CreateMentionNotification(
                            recipientId: profile.Id,
                            actorId: command.AuthorId,
                            pulseId: pulse.Id);
                        _unitOfWork.Notifications.Create(mentionNotification);
                        AppMetrics.RecordNotificationCreated("mention");
                    }
                }
                if (mentionResult.MentionedProfiles.Count > 0)
                {
                    await _unitOfWork.SaveChangesAsync(cancellationToken);
                }
                mentionCount = mentionResult.Count;

                // 5. Generate link preview if URL detected
                var firstUrl = _linkPreviewService.ExtractFirstUrl(pulse.Content);
                if (firstUrl is not null)
                {
                    hasLink = true;
                    var previewData = await _linkPreviewService.FetchPreviewAsync(
                        firstUrl,
                        cancellationToken);

                    if (previewData is not null)
                    {
                        var linkPreview = PulseLinkPreview.Create(
                            pulseId: pulse.Id,
                            url: previewData.Url,
                            title: previewData.Title,
                            domain: previewData.Domain,
                            description: previewData.Description,
                            imageUrl: previewData.ImageUrl);

                        _unitOfWork.Pulses.CreateLinkPreview(linkPreview);
                        await _unitOfWork.SaveChangesAsync(cancellationToken);
                        AppMetrics.RecordLinkPreviewFetch(success: true);
                    }
                    else
                    {
                        AppMetrics.RecordLinkPreviewFetch(success: false);
                    }
                }

                // 6. Extract and process hashtags
                hashtagCount = await _contentProcessor.ProcessHashtagsAsync(
                    pulse.Id,
                    pulse.Content,
                    cancellationToken);

                // Commit transaction - all entities created successfully
                // Database state is now consistent: Pulse + Engagement + (optional) PulseImage + (optional) Mentions + (optional) Hashtags
                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                // Rollback on any error - no database records will be persisted
                await transaction.RollbackAsync(cancellationToken);

                // Clean up orphaned blob if it was uploaded but transaction failed
                // This prevents accumulating orphaned blobs in storage
                if (imageUrl is not null)
                {
                    try
                    {
                        await _blobStorageService.DeletePulseImageAsync(pulse.Id, cancellationToken);
                    }
                    catch
                    {
                        // Log but don't throw - cleanup is best effort
                        // The orphaned blob can be cleaned up by a background job if needed
                    }
                }

                throw;
            }

            // Record metrics and set span metadata
            AppMetrics.RecordPulseCreated(pulseType: "original", hasImage: hasImage);
            activity?.SetPulseMetadata(
                pulseType: "original",
                hasImage: hasImage,
                hasLink: hasLink,
                mentionCount: mentionCount,
                hashtagCount: hashtagCount);
            activity?.SetSuccess(true);

            return new CreatePulseResult(
                PulseId: pulse.Id,
                Content: pulse.Content,
                CreatedAt: pulse.CreatedAt,
                ImageUrl: imageUrl
            );
        }
        catch (Exception ex)
        {
            activity?.RecordError(ex);
            throw;
        }
    }
}
