// <auto-generated />
using System;
using Codewrinkles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codewrinkles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128063636_AddPulseLikes")]
    partial class AddPulseLikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Codewrinkles.Domain.Identity.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Identities_CreatedAt");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Identities_EmailNormalized");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Identities_IsActive");

                    b.ToTable("Identities", "identity");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Identity.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Handle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_Handle")
                        .HasFilter("[Handle] IS NOT NULL");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("IX_Profiles_IdentityId");

                    b.ToTable("Profiles", "identity");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.Pulse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ParentPulseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RepulsedPulseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Pulses_AuthorId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Pulses_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Pulses_IsDeleted");

                    b.HasIndex("ParentPulseId")
                        .HasDatabaseName("IX_Pulses_ParentPulseId")
                        .HasFilter("[ParentPulseId] IS NOT NULL");

                    b.HasIndex("RepulsedPulseId")
                        .HasDatabaseName("IX_Pulses_RepulsedPulseId")
                        .HasFilter("[RepulsedPulseId] IS NOT NULL");

                    b.ToTable("Pulses", "pulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.PulseEngagement", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReplyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RepulseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("PulseId");

                    b.ToTable("PulseEngagements", "pulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.PulseLike", b =>
                {
                    b.Property<Guid>("PulseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PulseId", "ProfileId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PulseLikes_CreatedAt");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("IX_PulseLikes_ProfileId");

                    b.ToTable("PulseLikes", "pulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Identity.Profile", b =>
                {
                    b.HasOne("Codewrinkles.Domain.Identity.Identity", "Identity")
                        .WithOne("Profile")
                        .HasForeignKey("Codewrinkles.Domain.Identity.Profile", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.Pulse", b =>
                {
                    b.HasOne("Codewrinkles.Domain.Identity.Profile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Codewrinkles.Domain.Pulse.Pulse", "ParentPulse")
                        .WithMany()
                        .HasForeignKey("ParentPulseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Codewrinkles.Domain.Pulse.Pulse", "RepulsedPulse")
                        .WithMany()
                        .HasForeignKey("RepulsedPulseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("ParentPulse");

                    b.Navigation("RepulsedPulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.PulseEngagement", b =>
                {
                    b.HasOne("Codewrinkles.Domain.Pulse.Pulse", "Pulse")
                        .WithOne("Engagement")
                        .HasForeignKey("Codewrinkles.Domain.Pulse.PulseEngagement", "PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.PulseLike", b =>
                {
                    b.HasOne("Codewrinkles.Domain.Identity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Codewrinkles.Domain.Pulse.Pulse", "Pulse")
                        .WithMany()
                        .HasForeignKey("PulseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Pulse");
                });

            modelBuilder.Entity("Codewrinkles.Domain.Identity.Identity", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Codewrinkles.Domain.Pulse.Pulse", b =>
                {
                    b.Navigation("Engagement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
