namespace Codewrinkles.Domain.Pulse;

public sealed class Hashtag
{
    // Properties
    public Guid Id { get; private set; }
    public string Tag { get; private set; }
    public string TagDisplay { get; private set; }
    public int PulseCount { get; private set; }
    public DateTimeOffset LastUsedAt { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }

    // Navigation property
    public ICollection<PulseHashtag> PulseHashtags { get; private set; } = [];

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Hashtag() { }
#pragma warning restore CS8618

    // Factory method for creating valid instances
    public static Hashtag Create(string tagDisplay)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tagDisplay, nameof(tagDisplay));

        var normalized = tagDisplay.Trim().ToLowerInvariant().TrimStart('#');

        return new Hashtag
        {
            // Id will be generated by EF Core using sequential GUID generation
            Tag = normalized,
            TagDisplay = tagDisplay.Trim().TrimStart('#'),
            PulseCount = 0,
            LastUsedAt = DateTimeOffset.UtcNow,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    // Public methods
    public void IncrementUsage()
    {
        PulseCount++;
        LastUsedAt = DateTimeOffset.UtcNow;
    }

    public void DecrementUsage()
    {
        if (PulseCount > 0)
            PulseCount--;
    }
}
