namespace Codewrinkles.Domain.Pulse;

public sealed class PulseImage
{
    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private PulseImage() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid PulseId { get; private set; }
    public string Url { get; private set; }
    public string? AltText { get; private set; }
    public int Width { get; private set; }
    public int Height { get; private set; }

    // Navigation property
    public Pulse Pulse { get; private set; }

    // Factory method
    public static PulseImage Create(Guid pulseId, string url, int width, int height, string? altText = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(url, nameof(url));

        if (width <= 0)
        {
            throw new ArgumentException("Width must be greater than 0", nameof(width));
        }

        if (height <= 0)
        {
            throw new ArgumentException("Height must be greater than 0", nameof(height));
        }

        return new PulseImage
        {
            // Id will be generated by EF Core using sequential GUID generation
            PulseId = pulseId,
            Url = url.Trim(),
            Width = width,
            Height = height,
            AltText = string.IsNullOrWhiteSpace(altText) ? null : altText.Trim()
        };
    }
}
