using Codewrinkles.Domain.Identity;

namespace Codewrinkles.Domain.Pulse;

public sealed class Pulse
{
    // Constants
    public const int MaxContentLength = 500;

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Pulse() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid AuthorId { get; private set; }
    public string Content { get; private set; }
    public Guid? RepulsedPulseId { get; private set; }
    public Guid? ParentPulseId { get; private set; }
    public PulseType Type { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime? UpdatedAt { get; private set; }
    public bool IsDeleted { get; private set; }

    // Navigation properties
    public Profile Author { get; private set; }
    public Pulse? RepulsedPulse { get; private set; }
    public Pulse? ParentPulse { get; private set; }
    public PulseEngagement Engagement { get; private set; }
    public PulseImage? Image { get; private set; }
    public PulseLinkPreview? LinkPreview { get; private set; }

    // Factory methods
    public static Pulse Create(Guid authorId, string content)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        var trimmedContent = content.Trim();

        if (trimmedContent.Length > MaxContentLength)
        {
            throw new ArgumentException(
                $"Pulse content cannot exceed {MaxContentLength} characters. Current length: {trimmedContent.Length}",
                nameof(content));
        }

        return new Pulse
        {
            // Id will be generated by EF Core using sequential GUID generation
            AuthorId = authorId,
            Content = trimmedContent,
            Type = PulseType.Original,
            RepulsedPulseId = null,
            ParentPulseId = null,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = null,
            IsDeleted = false
        };
    }

    public static Pulse CreateRepulse(Guid authorId, string content, Guid repulsedPulseId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        var trimmedContent = content.Trim();

        if (trimmedContent.Length > MaxContentLength)
        {
            throw new ArgumentException(
                $"Pulse content cannot exceed {MaxContentLength} characters. Current length: {trimmedContent.Length}",
                nameof(content));
        }

        return new Pulse
        {
            // Id will be generated by EF Core using sequential GUID generation
            AuthorId = authorId,
            Content = trimmedContent,
            Type = PulseType.Repulse,
            RepulsedPulseId = repulsedPulseId,
            ParentPulseId = null,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = null,
            IsDeleted = false
        };
    }

    public static Pulse CreateReply(Guid authorId, string content, Guid parentPulseId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        var trimmedContent = content.Trim();

        if (trimmedContent.Length > MaxContentLength)
        {
            throw new ArgumentException(
                $"Pulse content cannot exceed {MaxContentLength} characters. Current length: {trimmedContent.Length}",
                nameof(content));
        }

        return new Pulse
        {
            // Id will be generated by EF Core using sequential GUID generation
            AuthorId = authorId,
            Content = trimmedContent,
            Type = PulseType.Reply,
            RepulsedPulseId = null,
            ParentPulseId = parentPulseId,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = null,
            IsDeleted = false
        };
    }

    // Public methods
    public void MarkAsDeleted()
    {
        IsDeleted = true;
        UpdatedAt = DateTime.UtcNow;
    }
}
