using Codewrinkles.Domain.Identity;

namespace Codewrinkles.Domain.Pulse;

public sealed class PulseBookmark
{
    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private PulseBookmark() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid PulseId { get; private set; }
    public Guid ProfileId { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }

    // Navigation properties
    public Pulse Pulse { get; private set; }
    public Profile Profile { get; private set; }

    // Factory method
    public static PulseBookmark Create(Guid pulseId, Guid profileId)
    {
        ArgumentException.ThrowIfNullOrEmpty(pulseId.ToString(), nameof(pulseId));
        ArgumentException.ThrowIfNullOrEmpty(profileId.ToString(), nameof(profileId));

        return new PulseBookmark
        {
            // Id will be generated by EF Core using sequential GUID generation
            PulseId = pulseId,
            ProfileId = profileId,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }
}
