namespace Codewrinkles.Domain.Pulse;

public sealed class PulseLinkPreview
{
    // Properties
    public Guid Id { get; private set; }
    public Guid PulseId { get; private set; }
    public string Url { get; private set; }
    public string Title { get; private set; }
    public string? Description { get; private set; }
    public string? ImageUrl { get; private set; }
    public string Domain { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }

    // Navigation property
    public Pulse Pulse { get; private set; }

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private PulseLinkPreview() { }
#pragma warning restore CS8618

    // Factory method for creating valid instances
    public static PulseLinkPreview Create(
        Guid pulseId,
        string url,
        string title,
        string domain,
        string? description = null,
        string? imageUrl = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(url, nameof(url));
        ArgumentException.ThrowIfNullOrWhiteSpace(title, nameof(title));
        ArgumentException.ThrowIfNullOrWhiteSpace(domain, nameof(domain));

        return new PulseLinkPreview
        {
            // Id will be generated by EF Core using sequential GUID generation
            PulseId = pulseId,
            Url = url.Trim(),
            Title = title.Trim(),
            Description = description?.Trim(),
            ImageUrl = imageUrl?.Trim(),
            Domain = domain.Trim().ToLowerInvariant(),
            CreatedAt = DateTimeOffset.UtcNow
        };
    }
}
