using Codewrinkles.Domain.Identity;

namespace Codewrinkles.Domain.Notification;

public sealed class Notification
{
    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Notification() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid RecipientId { get; private set; }
    public Guid ActorId { get; private set; }
    public NotificationType Type { get; private set; }
    public Guid? EntityId { get; private set; }
    public string? EntityType { get; private set; }
    public bool IsRead { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime? ReadAt { get; private set; }

    // Navigation properties
    public Profile Recipient { get; private set; }
    public Profile Actor { get; private set; }

    // Factory methods
    public static Notification CreateLikeNotification(
        Guid recipientId,
        Guid actorId,
        Guid pulseId)
    {
        return new Notification
        {
            // Id will be generated by EF Core using sequential GUID generation
            RecipientId = recipientId,
            ActorId = actorId,
            Type = NotificationType.PulseLike,
            EntityId = pulseId,
            EntityType = "Pulse",
            IsRead = false,
            CreatedAt = DateTime.UtcNow,
            ReadAt = null
        };
    }

    public static Notification CreateReplyNotification(
        Guid recipientId,
        Guid actorId,
        Guid pulseId)
    {
        return new Notification
        {
            RecipientId = recipientId,
            ActorId = actorId,
            Type = NotificationType.PulseReply,
            EntityId = pulseId,
            EntityType = "Pulse",
            IsRead = false,
            CreatedAt = DateTime.UtcNow,
            ReadAt = null
        };
    }

    public static Notification CreateRepulseNotification(
        Guid recipientId,
        Guid actorId,
        Guid pulseId)
    {
        return new Notification
        {
            RecipientId = recipientId,
            ActorId = actorId,
            Type = NotificationType.PulseRepulse,
            EntityId = pulseId,
            EntityType = "Pulse",
            IsRead = false,
            CreatedAt = DateTime.UtcNow,
            ReadAt = null
        };
    }

    public static Notification CreateMentionNotification(
        Guid recipientId,
        Guid actorId,
        Guid pulseId)
    {
        return new Notification
        {
            RecipientId = recipientId,
            ActorId = actorId,
            Type = NotificationType.PulseMention,
            EntityId = pulseId,
            EntityType = "Pulse",
            IsRead = false,
            CreatedAt = DateTime.UtcNow,
            ReadAt = null
        };
    }

    public static Notification CreateFollowNotification(
        Guid recipientId,
        Guid actorId)
    {
        return new Notification
        {
            RecipientId = recipientId,
            ActorId = actorId,
            Type = NotificationType.Follow,
            EntityId = null,
            EntityType = "Profile",
            IsRead = false,
            CreatedAt = DateTime.UtcNow,
            ReadAt = null
        };
    }

    // Public methods
    public void MarkAsRead()
    {
        if (!IsRead)
        {
            IsRead = true;
            ReadAt = DateTime.UtcNow;
        }
    }
}
