namespace Codewrinkles.Domain.Identity;

public sealed class Identity
{
    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Identity() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public string Email { get; private set; }
    public string EmailNormalized { get; private set; }
    public string? PasswordHash { get; private set; }
    public bool IsEmailVerified { get; private set; }
    public bool IsActive { get; private set; }
    public UserRole Role { get; private set; }
    public int FailedLoginAttempts { get; private set; }
    public DateTimeOffset? LockedUntil { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }
    public DateTimeOffset? LastLoginAt { get; private set; }

    // Navigation properties
    public Profile Profile { get; private set; }
    public ICollection<ExternalLogin> ExternalLogins { get; private set; } = [];

    // Factory methods
    public static Identity Create(string email, string passwordHash)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(email, nameof(email));
        ArgumentException.ThrowIfNullOrWhiteSpace(passwordHash, nameof(passwordHash));

        return new Identity
        {
            // Id will be generated by EF Core using sequential GUID generation
            Email = email.Trim().ToLowerInvariant(),
            EmailNormalized = email.Trim().ToUpperInvariant(),
            PasswordHash = passwordHash,
            IsEmailVerified = false,
            IsActive = true,
            Role = UserRole.User,
            FailedLoginAttempts = 0,
            LockedUntil = null,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
            LastLoginAt = null
        };
    }

    public static Identity CreateFromOAuth(string email, bool isEmailVerified)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(email);

        return new Identity
        {
            Email = email.Trim(),
            EmailNormalized = email.Trim().ToLowerInvariant(),
            PasswordHash = null,  // No password for OAuth-only accounts
            IsEmailVerified = isEmailVerified,
            IsActive = true,
            FailedLoginAttempts = 0,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
            Role = UserRole.User
        };
    }

    // Public methods
    public void MarkEmailAsVerified()
    {
        IsEmailVerified = true;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void RecordSuccessfulLogin()
    {
        FailedLoginAttempts = 0;
        LockedUntil = null;
        LastLoginAt = DateTimeOffset.UtcNow;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void RecordFailedLogin()
    {
        FailedLoginAttempts++;
        UpdatedAt = DateTimeOffset.UtcNow;

        // Lock account after 5 failed attempts for 15 minutes
        if (FailedLoginAttempts >= 5)
        {
            LockedUntil = DateTimeOffset.UtcNow.AddMinutes(15);
        }
    }

    public bool IsLockedOut()
    {
        return LockedUntil.HasValue && LockedUntil.Value > DateTimeOffset.UtcNow;
    }

    public void Suspend()
    {
        IsActive = false;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void Activate()
    {
        IsActive = true;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void ChangePassword(string newPasswordHash)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(newPasswordHash, nameof(newPasswordHash));

        PasswordHash = newPasswordHash;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void PromoteToAdmin()
    {
        Role = UserRole.Admin;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public bool HasOAuthProvider(OAuthProvider provider)
        => ExternalLogins.Any(el => el.Provider == provider);

    public bool CanLoginWithPassword()
        => !string.IsNullOrWhiteSpace(PasswordHash);

    public bool IsOAuthOnly()
        => string.IsNullOrWhiteSpace(PasswordHash) && ExternalLogins.Any();
}
