namespace Codewrinkles.Domain.Identity;

public sealed class Profile
{
    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Profile() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid IdentityId { get; private set; }
    public string Name { get; private set; }
    public string? Handle { get; private set; }
    public string? Bio { get; private set; }
    public string? AvatarUrl { get; private set; }
    public string? Location { get; private set; }
    public string? WebsiteUrl { get; private set; }
    public bool OnboardingCompleted { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    // Navigation property
    public Identity Identity { get; private set; }

    // Factory method
    public static Profile Create(Guid identityId, string name, string? handle = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name, nameof(name));

        var finalHandle = string.IsNullOrWhiteSpace(handle)
            ? GenerateHandleFromName(name)
            : handle.Trim().ToLowerInvariant();

        return new Profile
        {
            // Id will be generated by EF Core using sequential GUID generation
            IdentityId = identityId,
            Name = name.Trim(),
            Handle = finalHandle,
            Bio = null,
            AvatarUrl = null,
            Location = null,
            WebsiteUrl = null,
            OnboardingCompleted = false,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
    }

    // Public methods
    public void UpdateProfile(string? name, string? bio, string? avatarUrl)
    {
        if (!string.IsNullOrWhiteSpace(name))
        {
            Name = name.Trim();
        }

        Bio = string.IsNullOrWhiteSpace(bio) ? null : bio.Trim();
        AvatarUrl = string.IsNullOrWhiteSpace(avatarUrl) ? null : avatarUrl.Trim();
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void UpdateProfileDetails(string name, string? bio, string? handle, string? location, string? websiteUrl)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name, nameof(name));

        Name = name.Trim();
        Bio = string.IsNullOrWhiteSpace(bio) ? null : bio.Trim();

        if (!string.IsNullOrWhiteSpace(handle))
        {
            Handle = handle.Trim().ToLowerInvariant();
        }

        Location = string.IsNullOrWhiteSpace(location) ? null : location.Trim();
        WebsiteUrl = string.IsNullOrWhiteSpace(websiteUrl) ? null : websiteUrl.Trim();

        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void UpdateAvatarUrl(string? avatarUrl)
    {
        AvatarUrl = string.IsNullOrWhiteSpace(avatarUrl) ? null : avatarUrl.Trim();
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void CompleteOnboarding()
    {
        OnboardingCompleted = true;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    // Private methods
    private static string GenerateHandleFromName(string name)
    {
        // Remove special characters, keep only alphanumeric
        var cleaned = new string(name.Where(c => char.IsLetterOrDigit(c) || c == ' ').ToArray());

        // Replace spaces with underscores
        var handle = cleaned.Replace(' ', '_').ToLowerInvariant();

        // Ensure minimum length
        return handle.Length >= 3 ? handle : $"{handle}_user";
    }
}
