namespace Codewrinkles.Domain.Nova;

/// <summary>
/// Represents a background job for ingesting content (PDF, transcript, docs scrape).
/// </summary>
public sealed class ContentIngestionJob
{
    // Constants
    public const int MaxTitleLength = 500;
    public const int MaxUrlLength = 2000;
    public const int MaxErrorMessageLength = 4000;
    public const int MaxAuthorLength = 200;
    public const int MaxTechnologyLength = 50;
    public const int MaxParentDocumentIdLength = 500;

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618
    private ContentIngestionJob() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public ContentSource Source { get; private set; }
    public IngestionJobStatus Status { get; private set; }
    public string Title { get; private set; }
    public string ParentDocumentId { get; private set; }  // Used to group chunks

    // Source-specific metadata
    public string? Author { get; private set; }           // For books
    public string? Technology { get; private set; }       // For docs
    public string? SourceUrl { get; private set; }        // URL for docs/YouTube
    public int? MaxPages { get; private set; }            // For docs scraping

    // Progress tracking
    public int ChunksCreated { get; private set; }
    public int? TotalPages { get; private set; }
    public int? PagesProcessed { get; private set; }

    // Error handling
    public string? ErrorMessage { get; private set; }

    // Timestamps
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset? StartedAt { get; private set; }
    public DateTimeOffset? CompletedAt { get; private set; }

    // Factory methods

    /// <summary>
    /// Creates a job for ingesting a PDF book.
    /// </summary>
    public static ContentIngestionJob CreateForPdf(string title, string author)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        ArgumentException.ThrowIfNullOrWhiteSpace(author);

        return new ContentIngestionJob
        {
            // Id will be generated by EF Core using sequential GUID generation
            Source = ContentSource.Book,
            Status = IngestionJobStatus.Queued,
            Title = Truncate(title.Trim(), MaxTitleLength),
            ParentDocumentId = $"book_{Guid.NewGuid():N}",
            Author = Truncate(author.Trim(), MaxAuthorLength),
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a job for ingesting official documentation from a PDF.
    /// </summary>
    public static ContentIngestionJob CreateForPdfDocs(string title, string technology)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        ArgumentException.ThrowIfNullOrWhiteSpace(technology);

        return new ContentIngestionJob
        {
            // Id will be generated by EF Core using sequential GUID generation
            Source = ContentSource.OfficialDocs,
            Status = IngestionJobStatus.Queued,
            Title = Truncate(title.Trim(), MaxTitleLength),
            ParentDocumentId = $"docs_{Guid.NewGuid():N}",
            Technology = technology.ToLowerInvariant(),
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a job for ingesting a YouTube transcript.
    /// </summary>
    public static ContentIngestionJob CreateForYouTube(string videoId, string videoUrl, string title)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(videoId);
        ArgumentException.ThrowIfNullOrWhiteSpace(title);

        return new ContentIngestionJob
        {
            // Id will be generated by EF Core using sequential GUID generation
            Source = ContentSource.YouTube,
            Status = IngestionJobStatus.Queued,
            Title = Truncate(title.Trim(), MaxTitleLength),
            ParentDocumentId = $"yt_{videoId}",
            SourceUrl = videoUrl,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a job for scraping documentation.
    /// </summary>
    public static ContentIngestionJob CreateForDocs(string homepageUrl, string technology, int maxPages = 100)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(homepageUrl);
        ArgumentException.ThrowIfNullOrWhiteSpace(technology);

        var uri = new Uri(homepageUrl);
        return new ContentIngestionJob
        {
            // Id will be generated by EF Core using sequential GUID generation
            Source = ContentSource.OfficialDocs,
            Status = IngestionJobStatus.Queued,
            Title = $"{technology} Docs - {uri.Host}",
            ParentDocumentId = $"docs_{Guid.NewGuid():N}",
            SourceUrl = homepageUrl,
            Technology = technology.ToLowerInvariant(),
            MaxPages = maxPages,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    // Public methods

    /// <summary>
    /// Marks the job as processing.
    /// </summary>
    public void MarkAsProcessing()
    {
        Status = IngestionJobStatus.Processing;
        StartedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Updates progress during processing.
    /// </summary>
    public void UpdateProgress(int pagesProcessed, int totalPages)
    {
        PagesProcessed = pagesProcessed;
        TotalPages = totalPages;
    }

    /// <summary>
    /// Increments the count of chunks created.
    /// </summary>
    public void IncrementChunksCreated(int count = 1)
    {
        ChunksCreated += count;
    }

    /// <summary>
    /// Marks the job as completed successfully.
    /// </summary>
    public void MarkAsCompleted(int totalChunks)
    {
        Status = IngestionJobStatus.Completed;
        ChunksCreated = totalChunks;
        CompletedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Marks the job as failed with an error message.
    /// </summary>
    public void MarkAsFailed(string errorMessage)
    {
        Status = IngestionJobStatus.Failed;
        ErrorMessage = Truncate(errorMessage, MaxErrorMessageLength);
        CompletedAt = DateTimeOffset.UtcNow;
    }

    // Private helper methods
    private static string Truncate(string value, int maxLength)
    {
        return value.Length <= maxLength ? value : value[..maxLength];
    }
}
