using Codewrinkles.Domain.Identity;

namespace Codewrinkles.Domain.Nova;

/// <summary>
/// Represents a Nova conversation session between a user and the AI coach.
/// </summary>
public sealed class ConversationSession
{
    // Constants
    public const int MaxTitleLength = 200;

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private ConversationSession() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid ProfileId { get; private set; }
    public string? Title { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset LastMessageAt { get; private set; }
    public bool IsDeleted { get; private set; }

    // Navigation properties
    public Profile Owner { get; private set; }
    public ICollection<Message> Messages { get; private set; }

    // Factory methods
    public static ConversationSession Create(Guid profileId, string? title = null)
    {
        var trimmedTitle = title?.Trim();

        if (trimmedTitle is not null && trimmedTitle.Length > MaxTitleLength)
        {
            throw new ArgumentException(
                $"Conversation title cannot exceed {MaxTitleLength} characters.",
                nameof(title));
        }

        return new ConversationSession
        {
            // Id will be generated by EF Core using sequential GUID generation
            ProfileId = profileId,
            Title = trimmedTitle,
            CreatedAt = DateTimeOffset.UtcNow,
            LastMessageAt = DateTimeOffset.UtcNow,
            IsDeleted = false,
            Messages = new List<Message>()
        };
    }

    // Public methods
    public void UpdateTitle(string title)
    {
        var trimmedTitle = title.Trim();

        if (trimmedTitle.Length > MaxTitleLength)
        {
            throw new ArgumentException(
                $"Conversation title cannot exceed {MaxTitleLength} characters.",
                nameof(title));
        }

        Title = trimmedTitle;
    }

    public void UpdateLastMessageAt()
    {
        LastMessageAt = DateTimeOffset.UtcNow;
    }

    public void MarkAsDeleted()
    {
        IsDeleted = true;
    }
}
