using Codewrinkles.Domain.Identity;

namespace Codewrinkles.Domain.Nova;

/// <summary>
/// Nova-specific learner profile that extends the global identity.Profile
/// with learning preferences and AI-extracted insights.
/// </summary>
public sealed class LearnerProfile
{
    // Constants
    public const int MaxRoleLength = 200;
    public const int MaxTechStackLength = 500;
    public const int MaxProjectLength = 500;
    public const int MaxGoalsLength = 1000;
    public const int MaxInsightsLength = 1000;

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private LearnerProfile() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid ProfileId { get; private set; }

    // Professional Background
    public string? CurrentRole { get; private set; }
    public int? ExperienceYears { get; private set; }
    public string? PrimaryTechStack { get; private set; }
    public string? CurrentProject { get; private set; }

    // Learning Preferences
    public string? LearningGoals { get; private set; }
    public LearningStyle? LearningStyle { get; private set; }
    public PreferredPace? PreferredPace { get; private set; }

    // AI-Extracted Insights (updated by memory pipeline)
    public string? IdentifiedStrengths { get; private set; }
    public string? IdentifiedStruggles { get; private set; }

    // Metadata
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    // Navigation property
    public Profile Profile { get; private set; }

    // Factory method
    public static LearnerProfile Create(Guid profileId)
    {
        return new LearnerProfile
        {
            // Id will be generated by EF Core using sequential GUID generation
            ProfileId = profileId,
            CurrentRole = null,
            ExperienceYears = null,
            PrimaryTechStack = null,
            CurrentProject = null,
            LearningGoals = null,
            LearningStyle = null,
            PreferredPace = null,
            IdentifiedStrengths = null,
            IdentifiedStruggles = null,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
    }

    // Public methods
    public void UpdateProfessionalBackground(
        string? currentRole,
        int? experienceYears,
        string? primaryTechStack,
        string? currentProject)
    {
        CurrentRole = TruncateAndTrim(currentRole, MaxRoleLength);
        ExperienceYears = experienceYears;
        PrimaryTechStack = TruncateAndTrim(primaryTechStack, MaxTechStackLength);
        CurrentProject = TruncateAndTrim(currentProject, MaxProjectLength);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void UpdateLearningPreferences(
        string? learningGoals,
        LearningStyle? learningStyle,
        PreferredPace? preferredPace)
    {
        LearningGoals = TruncateAndTrim(learningGoals, MaxGoalsLength);
        LearningStyle = learningStyle;
        PreferredPace = preferredPace;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void UpdateInsights(string? strengths, string? struggles)
    {
        IdentifiedStrengths = TruncateAndTrim(strengths, MaxInsightsLength);
        IdentifiedStruggles = TruncateAndTrim(struggles, MaxInsightsLength);
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    public void UpdateAll(
        string? currentRole,
        int? experienceYears,
        string? primaryTechStack,
        string? currentProject,
        string? learningGoals,
        LearningStyle? learningStyle,
        PreferredPace? preferredPace)
    {
        CurrentRole = TruncateAndTrim(currentRole, MaxRoleLength);
        ExperienceYears = experienceYears;
        PrimaryTechStack = TruncateAndTrim(primaryTechStack, MaxTechStackLength);
        CurrentProject = TruncateAndTrim(currentProject, MaxProjectLength);
        LearningGoals = TruncateAndTrim(learningGoals, MaxGoalsLength);
        LearningStyle = learningStyle;
        PreferredPace = preferredPace;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Checks if the profile has any user-entered data (not just AI-extracted).
    /// </summary>
    public bool HasUserData()
    {
        return !string.IsNullOrWhiteSpace(CurrentRole)
            || ExperienceYears.HasValue
            || !string.IsNullOrWhiteSpace(PrimaryTechStack)
            || !string.IsNullOrWhiteSpace(LearningGoals)
            || LearningStyle.HasValue
            || PreferredPace.HasValue;
    }

    // Private methods
    private static string? TruncateAndTrim(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        var trimmed = value.Trim();
        return trimmed.Length > maxLength ? trimmed[..maxLength] : trimmed;
    }
}
