namespace Codewrinkles.Domain.Nova;

/// <summary>
/// Represents a single message in a Nova conversation.
/// </summary>
public sealed class Message
{
    // Constants
    public const int MaxContentLength = 100_000; // ~25k tokens worth of text

    // Private parameterless constructor for EF Core materialization only
    // EF Core will populate all properties via reflection when loading from database
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
    private Message() { }
#pragma warning restore CS8618

    // Properties
    public Guid Id { get; private set; }
    public Guid SessionId { get; private set; }
    public MessageRole Role { get; private set; }
    public string Content { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public int? TokensUsed { get; private set; }
    public string? ModelUsed { get; private set; }

    // Navigation properties
    public ConversationSession Session { get; private set; }

    // Factory methods
    public static Message CreateUserMessage(Guid sessionId, string content)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        var trimmedContent = content.Trim();

        if (trimmedContent.Length > MaxContentLength)
        {
            throw new ArgumentException(
                $"Message content cannot exceed {MaxContentLength} characters.",
                nameof(content));
        }

        return new Message
        {
            // Id will be generated by EF Core using sequential GUID generation
            SessionId = sessionId,
            Role = MessageRole.User,
            Content = trimmedContent,
            CreatedAt = DateTimeOffset.UtcNow,
            TokensUsed = null,
            ModelUsed = null
        };
    }

    public static Message CreateAssistantMessage(
        Guid sessionId,
        string content,
        int? tokensUsed = null,
        string? modelUsed = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        return new Message
        {
            // Id will be generated by EF Core using sequential GUID generation
            SessionId = sessionId,
            Role = MessageRole.Assistant,
            Content = content.Trim(),
            CreatedAt = DateTimeOffset.UtcNow,
            TokensUsed = tokensUsed,
            ModelUsed = modelUsed
        };
    }

    public static Message CreateSystemMessage(Guid sessionId, string content)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(content, nameof(content));

        return new Message
        {
            // Id will be generated by EF Core using sequential GUID generation
            SessionId = sessionId,
            Role = MessageRole.System,
            Content = content.Trim(),
            CreatedAt = DateTimeOffset.UtcNow,
            TokensUsed = null,
            ModelUsed = null
        };
    }
}
